import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import { arExtra, enExtra, frExtra } from './i18n-extra'
import { arMedical, enMedical, frMedical } from './i18n-medical'
import { arSimple, enSimple, frSimple } from './i18n-simple'

export const supportedLanguages = ['fr', 'en', 'ar'] as const
export type AppLanguage = typeof supportedLanguages[number]

const fr = {
  common: {
    back: 'Retour', add: 'Ajouter', create: 'Créer', edit: 'Modifier', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', close: 'Fermer', search: 'Rechercher', select: 'Sélectionner', all: 'Tous', none: 'Aucun', yes: 'Oui', no: 'Non', active: 'Actif', inactive: 'Inactif', available: 'Disponible', unavailable: 'Indisponible', actions: 'Actions', status: 'Statut', date: 'Date', time: 'Heure', client: 'Client', practitioner: 'Praticien', service: 'Acte', services: 'Actes', product: 'Produit', products: 'Produits', price: 'Prix', duration: 'Durée', category: 'Catégorie', phone: 'Téléphone', email: 'Email', name: 'Nom', firstName: 'Prénom', lastName: 'Nom', password: 'Mot de passe', notes: 'Notes', total: 'Total', subtotal: 'Sous-total', payment: 'Paiement', loading: 'Chargement...', error: 'Erreur', success: 'Succès', required: 'Requis', today: "Aujourd'hui", yesterday: 'Hier', week: 'Cette semaine', month: 'Ce mois', customPeriod: 'Période personnalisée', noData: 'Aucune donnée disponible', reset: 'Réinitialiser', view: 'Voir', print: 'Imprimer', profile: 'Profil', logout: 'Déconnexion', language: 'Langue', french: 'Français', english: 'English', arabic: 'العربية'
  },
  nav: {
    invoices: 'Factures', messages: 'Messages', audit: 'Journal d’audit', home: 'Accueil', dashboard: 'Tableau de bord', allCabinets: 'Tous les cabinets', practitioners: 'Praticiens', services: 'Actes', products: 'Produits', productSales: 'Ventes produits', appointments: 'Rendez-vous', clients: 'Clients', history: 'Historique', myServices: 'Mes actes', myStats: 'Mes statistiques', users: 'Utilisateurs', plans: 'Plans SaaS', payroll: 'Paie', settings: 'Paramètres', permissions: 'Permissions', administration: 'Administration', selectedCabinet: 'Cabinet sélectionné', openMenu: 'Ouvrir le menu', closeMenu: 'Fermer le menu'
  },
  roles: { admin: 'Administrateur', superAdmin: 'Super Admin', practitioner: 'Praticien' },
  auth: {
    login: 'Connexion', register: 'Créer votre espace', subtitle: 'Accédez à votre espace de gestion', cabinetName: 'Nom du cabinet', emailAddress: 'Adresse email', firstName: 'Prénom', lastName: 'Nom', password: 'Mot de passe', signIn: 'Se connecter', signingIn: 'Connexion...', creating: 'Création...', startTrial: 'Démarrer mon essai gratuit', haveAccount: "J'ai déjà un compte", createAccount: 'Créer un compte', welcome: 'Bienvenue !', loginSuccess: 'Connexion réussie', loginFailed: 'Échec de la connexion', accessDenied: 'Accès refusé', invalidCredentials: 'Identifiants incorrects', registrationFailed: 'Inscription impossible', emailRequired: 'Email requis', invalidEmail: 'Email invalide', passwordRequired: 'Mot de passe requis', minChars: 'Minimum 4 caractères', demo: 'Démo : admin@practitioner.ma / admin123', practiceCreationRestricted: 'La création des cabinets est réservée au super administrateur.', headline: 'Gérez votre cabinet comme un pro', description: 'Suivez vos rendez-vous, vos actes et vos revenus en temps réel. Une plateforme complète pour les praticiens et gérants de cabinet.', revenueAccuracy: 'Précision CA', availability: 'Disponibilité', reports: 'Rapports'
  },
  home: {
    servicesEyebrow: 'NOS SERVICES', title: 'Mon espace', subtitle: 'Accès rapide aux fonctionnalités.', appointments: 'Rendez-vous', appointmentsDesc: 'Voir les rendez-vous et gérer la file.', newService: 'Nouvelle acte', newServiceDesc: 'Encaisser rapidement un acte.', productSale: 'Vente produits', productSaleDesc: 'Ajouter des produits et encaisser la vente.', history: 'Historique', historyDesc: 'Actes et produits vendus.', tickets: 'Tickets', ticketsDesc: 'Actes et produits du jour.'
  },
  appointment: {
    title: 'Rendez-vous', subtitle: 'Planification et suivi', new: 'Nouveau rendez-vous', edit: 'Modifier rendez-vous', next: 'Prochain rendez-vous', todayHistory: 'Historique du jour', todayCount: '{{count}} rendez-vous', noWaiting: 'Aucun client en attente.', noToday: "Aucun rendez-vous à traiter aujourd'hui", noHistory: "Aucun rendez-vous dans l’historique du jour", waitingRoom: "Salle d’attente", toProcess: 'À traiter', inProgress: 'En cours', completed: 'Terminé', cancelled: 'Annulé', absent: 'Absent', confirmed: 'Confirmé', clientArrived: 'Client arrivé', start: 'Démarrer', finish: 'Terminer', newSuccess: 'Rendez-vous créé', editSuccess: 'Rendez-vous modifié', statusSuccess: 'Statut mis à jour', optionalClient: 'Client (optionnel)', selectPlaceholder: 'Sélectionner', practitionerRequired: 'Praticien requis', serviceRequired: 'Acte requise', dateRequired: 'Date requise', timeRequired: 'Heure requise', more: '+{{count}} autres', noActivePractitioner: 'Aucun praticien actif.', anyPractitioner: 'Tout praticien', walkIn: 'Sans rendez-vous'
  },
  sale: {
    searchAll: 'Rechercher un acte ou un produit...', searchProduct: 'Rechercher un produit...', order: 'Commande ({{count}})', touchService: "Touchez un acte pour l'ajouter.", touchProduct: "Touchez un produit pour l'ajouter.", selectClient: 'Sélectionner', newClient: 'Nouveau client', noClient: 'Aucun client trouvé.', cash: 'Espèces', card: 'Carte', both: 'Les deux', checkout: 'Encaisser {{amount}}', serviceSaved: 'Acte enregistrée', productsSaved: 'Vente de produits enregistrée', paymentMismatch: 'Le total des paiements doit correspondre au total de la vente', noMatchingService: 'Aucun acte ne correspond à la recherche.', noMatchingProduct: 'Aucun produit ne correspond à la recherche.'
  },
  history: {
    title: 'Historique des ventes', subtitle: 'Consultez toutes les transactions de votre boutique.', dailyTicket: 'Ticket du jour', periodTicket: 'Ticket période', totalSales: 'Total des ventes', transactionCount: 'Nombre de transactions', itemsSold: 'Articles vendus', averageTransaction: 'Moyenne par transaction', searchPlaceholder: 'Rechercher une transaction, un client, un article...', period: 'Période', practitioner: 'Praticien', service: 'Acte', product: 'Produit', payment: 'Paiement', allPractitioners: 'Tous les praticiens', allServices: 'Toutes les actes', allProducts: 'Tous les produits', allPayments: 'Toutes les méthodes', transactions: 'Transactions', articles: 'Articles', paymentMethod: 'Méthode de paiement', noMatch: 'Aucune transaction ne correspond aux filtres.', display: 'Affichage de {{count}} transaction(s) · Page {{page}} sur {{pages}}', previous: 'Précédent', next: 'Suivant', saleDetails: 'Détails de la vente', noClient: 'Sans client', practitionerCommission: 'Commission praticien', cabinetRevenue: 'Revenu cabinet', ticket: 'Ticket'
  },
  payment: { CASH: 'Espèces', CARD: 'Carte', OTHER: 'Autre' },
  queue: { title: "File d'attente", subtitle: 'Clients avec rendez-vous et passages sans rendez-vous', addClient: 'Ajouter un client', empty: 'La file est vide.', added: 'Client ajouté à la file', addToQueue: 'Ajouter à la file', chooseService: 'Choisir un acte', waitingMinutes: 'Attente {{count}} min', arrivedMinutes: 'Arrivé il y a {{count}} min' },
  dashboard: { global: 'Vue globale', globalDescription: 'Pilotage de tous les cabinets et de l’activité réseau.', cabinets: 'Cabinets', workspace: 'Choisissez votre espace de travail', appointmentsDescription: "Voir le calendrier, les arrivées et la file d'attente.", servicesDescription: 'Enregistrer un acte avec le formulaire de caisse.', performance: 'Performance', title: 'Tableau de bord', sevenDays: '7 jours', thirtyDays: '30 jours', from: 'Du', to: 'Au', noTransactions: 'Aucune transaction sur cette période', date: 'Date', practitioner: 'Praticien', client: 'Client', services: 'Acte(s)', payment: 'Paiement' },
  clients: { title: 'Clients', count: '{{count}} client(s) enregistré(s)', search: 'Rechercher par nom ou téléphone...', empty: 'Aucun client trouvé', new: 'Nouveau client', never: 'Jamais', visits: 'Visites', spent: 'Total dépensé', lastVisit: 'Dernière visite', created: 'Client créé', firstName: 'Prénom', lastName: 'Nom', phone: 'Téléphone', email: 'Email' },
  productsPage: { title: 'Produits', subtitle: 'Catalogue des produits vendables.', add: 'Ajouter produit', search: 'Rechercher...', status: 'Statut', all: 'Tous', active: 'Actifs', inactive: 'Inactifs', table: 'Table', grid: 'Grille', empty: 'Aucun produit', addFirst: 'Ajouter le premier', available: 'Disponible', new: 'Nouveau produit', edit: 'Modifier le produit', priceMad: 'Prix (MAD) *', photo: 'Photo', remove: 'Retirer', deleted: 'Produit supprimé', created: 'Produit créé', updated: 'Produit modifié', nameRequired: 'Nom requis', priceInvalid: 'Prix invalide' },
  servicesPage: { title: 'Catalogue des actes', subtitle: 'Services globaux (SUPER_ADMIN)', add: 'Ajouter service', search: 'Rechercher...', category: 'Catégorie', allCategories: 'Toutes', status: 'Statut', all: 'Tous', active: 'Actifs', inactive: 'Inactifs', available: 'Disponibles', unavailable: 'Indisponibles', table: 'Table', grid: 'Grille', empty: 'Aucun service dans le catalogue', addFirst: 'Ajouter le premier', emptyCabinet: 'Aucun acte enregistrée', createService: 'Créer un acte', addFromCatalog: 'Ajouter depuis catalogue', addService: 'Ajouter acte', service: 'Service', duration: 'Durée', price: 'Prix', new: 'Nouveau service', edit: 'Modifier le service', newCabinet: 'Nouvelle acte', editCabinet: 'Modifier la acte', nameRequired: 'Nom requis', priceInvalid: 'Prix invalide', durationInvalid: 'Durée invalide', added: 'Service ajouté au catalogue', created: 'Acte créée', updated: 'Acte modifiée', statusUpdated: 'Statut mis à jour', photo: 'Photo', description: 'Description', activeService: 'Service actif', availableService: 'Acte disponible / active', remove: 'Retirer', selectAll: 'Tout sélectionner', catalogHelp: 'Sélectionnez les actes et définissez leur prix pour ce cabinet.', alreadyAdded: 'Déjà ajoutée', changePhoto: 'Changer la photo', addPhoto: 'Ajouter une photo', upload: 'Envoi...', undefinedDuration: 'Durée non définie', clickPhoto: 'Cliquez sur la photo', emptyCatalog: 'Le catalogue est vide.', save: 'Enregistrer', saving: 'Enregistrement...', savedCount: 'Enregistrer ({{count}})', selectOne: 'Sélectionnez au moins un acte',
    coupe: 'Coupe', barbe: 'Barbe', forfait: 'Forfait', soin: 'Soin', autre: 'Autre' },
  practitionersPage: { title: 'Praticiens', subtitle: "Gérez l'équipe du cabinet", add: 'Ajouter praticien', empty: 'Aucun praticien enregistré', addFirst: 'Ajouter le premier', created: 'Praticien créé avec succès', updated: 'Praticien modifié avec succès', activated: 'Praticien activé', deactivated: 'Praticien désactivé', firstNameRequired: 'Prénom requis', lastNameRequired: 'Nom requis', emailInvalid: 'Email invalide', rateRequired: '0-100 % requis', salaryInvalid: 'Salaire invalide', disableTitle: 'Désactiver ce praticien ?', enableTitle: 'Activer ce praticien ?', disableDescription: 'Il ne pourra plus être sélectionné pour de nouvelles actes.', enableDescription: 'Il sera de nouveau disponible pour les actes.', commission: 'Commission', salary: 'Salaire fixe', mixed: 'Mixte' },
  salePage: { searchAll: 'Rechercher un acte ou un produit...', searchProduct: 'Rechercher un produit...', select: 'Sélectionner', noPractitioner: 'Aucun praticien actif.', noServiceMatch: 'Aucun acte ne correspond à la recherche.', noProductMatch: 'Aucun produit ne correspond à la recherche.', client: 'Client', close: 'Fermer', clientSearch: 'Nom ou téléphone', noClient: 'Aucun client trouvé.', newClient: 'Nouveau client', order: 'Commande ({{count}})', touchProduct: 'un produit', touchService: 'un acte', subtotal: 'Sous-total', both: 'Les deux', paymentMismatch: 'Le total des paiements doit correspondre au total de la acte', clientRequired: 'Prénom, nom et téléphone sont requis pour créer un client', savedProduct: 'Vente de produits enregistrée', savedService: 'Acte enregistrée', checkout: 'Encaisser {{amount}}' },
  reportsPage: { title: 'Rapports', subtitle: 'Rapport journalier détaillé', reportDate: 'Date du rapport', print: 'Imprimer', download: 'Télécharger PDF', loadDate: 'Chargez une date pour voir le rapport', daily: 'Rapport journalier', revenue: "Chiffre d'affaires", services: 'Actes', commissions: 'Commissions', net: 'Revenu net', breakdown: 'Décomposition par praticien', noPractitioners: 'Aucun praticien sur cette période', details: 'Détail des transactions ({{count}})', noTransactions: 'Aucune transaction', hour: 'Heure', cabinetRevenue: 'Revenus cabinet' },
  payrollPage: { title: 'Paie', subtitle: 'Calculez les commissions et suivez les règlements des praticiens.', newPeriod: 'Nouvelle période', start: 'Début', end: 'Fin', create: 'Créer et calculer', created: 'Période créée', base: 'Base', net: 'Net', paid: 'Payé', approved: 'Approuvé', pending: 'En attente', range: 'au' },
  adminPage: { usersTitle: 'Utilisateurs', newUser: 'Nouvel utilisateur', noUsers: 'Aucun utilisateur', created: 'Utilisateur créé', updated: 'Utilisateur mis à jour', deleted: 'Utilisateur supprimé', createFailed: 'Création impossible', deleteFailed: 'Suppression impossible', deleteUser: "Supprimer l’utilisateur ?", deleteUserDescription: 'Cette action désactive l’utilisateur et le retire de la liste.', planPricing: 'Pricing', planPricingSubtitle: 'Choisissez le plan adapté à votre cabinet.', noPlans: 'Aucun plan disponible', current: 'Actuel', perMonth: '/ mois', commitment: 'Engagement {{months}} mois', users: '{{count}} utilisateurs', practitioners: '{{count}} praticiens', currentPlan: 'Plan actuel', choose: 'Choisir', permissions: 'Permissions', permissionSubtitle: 'Configurez les permissions par rôle. Elles seront ensuite filtrées par les permissions du plan.', role: 'Rôle', newRole: 'Nouveau rôle', delete: 'Supprimer', selectAll: 'Tout sélectionner', deselectAll: 'Tout désélectionner', saved: 'Permissions mises à jour', deletedRole: 'Rôle supprimé' },
  settings: { subtitle: 'Gérez les informations du cabinet et votre compte', cabinetTab: 'Cabinet', accountTab: 'Compte', billingTab: 'Abonnement', cabinetInfo: 'Informations du cabinet', cabinetInfoDescription: 'Ces informations apparaîtront sur les tickets et les rapports.', cabinetName: 'Nom du cabinet', address: 'Adresse', currency: 'Devise', save: 'Enregistrer', billingDescription: 'Gérez le plan et le renouvellement automatique du cabinet.', expiredOn: 'Expiré le {{date}}', expiresToday: "Expire aujourd'hui ({{date}})", expiresIn: 'Expire le {{date}} ({{days}} jour(s) restant)', noExpiration: 'Expiration : Non définie', upgrade: 'Mettre à niveau', renew: 'Renouveler', noPlan: 'Aucun plan associé.', choosePlan: 'Choisir un plan', profile: 'Profil utilisateur', profileDescription: 'Vos informations de connexion', changePassword: 'Modifier le mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le nouveau mot de passe', changePasswordButton: 'Changer le mot de passe', passwordMismatch: 'Les mots de passe ne correspondent pas', saved: 'Informations enregistrées' },
  table: { rank: '#', practitioner: 'Praticien', serviceCount: 'Actes', revenue: "Chiffre d'affaires", commission: 'Commission', performance: 'Performance', phone: 'Téléphone', remuneration: 'Rémunération', rateSalary: 'Taux / Salaire', date: 'Date', items: 'Articles', paymentMethod: 'Méthode de paiement', total: 'Total', cabinet: 'Cabinet', plan: 'Plan', users: 'Utilisateurs', clients: 'Clients', user: 'Utilisateur', admin: 'Admin', role: 'Rôle', limits: 'Limites', permissions: 'Permissions', actions: 'Actions', hour: 'Heure', cabinetRevenue: 'Revenus cabinet' },
  status: { PENDING: 'À traiter', CONFIRMED: 'Confirmé', REMINDER_SENT: 'Rappel envoyé', WAITING: "Salle d’attente", IN_PROGRESS: 'En cours', COMPLETED: 'Terminé', CANCELLED: 'Annulé', NO_SHOW: 'Absent' },
  errors: { notFoundTitle: 'Page introuvable', notFoundDescription: "Cette page n'existe pas ou a été déplacée. Retournez à l'accueil pour continuer.", permissionTitle: 'Permission refusée', permissionDescription: "Vous n'avez pas l'autorisation d'accéder à cette page." },
  crud: {
    addFromCatalog: 'Ajouter depuis le catalogue', addService: 'Ajouter acte', addProduct: 'Ajouter produit', newService: 'Nouvelle acte', newProduct: 'Nouveau produit', catalogTitle: 'Catalogue des actes', catalogHelp: 'Sélectionnez les actes et définissez leur prix pour ce cabinet.', selectAll: 'Tout sélectionner', alreadyAdded: 'Déjà ajoutée', clickPhoto: 'Cliquez sur la photo', addPhoto: 'Ajouter une photo', changePhoto: 'Changer la photo', upload: 'Envoi...', recordCount: '{{count}} élément(s) enregistré(s)', emptyCatalog: 'Le catalogue est vide.', ratesServices: 'Tarifs et services proposés'
  }
}

const en = {
  common: {
    back: 'Back', add: 'Add', create: 'Create', edit: 'Edit', save: 'Save', cancel: 'Cancel', delete: 'Delete', close: 'Close', search: 'Search', select: 'Select', all: 'All', none: 'None', yes: 'Yes', no: 'No', active: 'Active', inactive: 'Inactive', available: 'Available', unavailable: 'Unavailable', actions: 'Actions', status: 'Status', date: 'Date', time: 'Time', client: 'Client', practitioner: 'Practitioner', service: 'Service', services: 'Services', product: 'Product', products: 'Products', price: 'Price', duration: 'Duration', category: 'Category', phone: 'Phone', email: 'Email', name: 'Name', firstName: 'First name', lastName: 'Last name', password: 'Password', notes: 'Notes', total: 'Total', subtotal: 'Subtotal', payment: 'Payment', loading: 'Loading...', error: 'Error', success: 'Success', required: 'Required', today: 'Today', yesterday: 'Yesterday', week: 'This week', month: 'This month', customPeriod: 'Custom period', noData: 'No data available', reset: 'Reset', view: 'View', print: 'Print', profile: 'Profile', logout: 'Log out', language: 'Language', french: 'Français', english: 'English', arabic: 'العربية'
  },
  nav: {
    invoices: 'Invoices', messages: 'Messages', audit: 'Audit log', home: 'Home', dashboard: 'Dashboard', allCabinets: 'All cabinets', practitioners: 'Practitioners', services: 'Services', products: 'Products', productSales: 'Product sales', appointments: 'Appointments', clients: 'Clients', history: 'History', myServices: 'My services', myStats: 'My statistics', users: 'Users', plans: 'SaaS plans', payroll: 'Payroll', settings: 'Settings', permissions: 'Permissions', administration: 'Administration', selectedCabinet: 'Selected cabinet', openMenu: 'Open menu', closeMenu: 'Close menu'
  },
  roles: { admin: 'Administrator', superAdmin: 'Super Admin', practitioner: 'Practitioner' },
  auth: {
    login: 'Sign in', register: 'Create your workspace', subtitle: 'Access your management workspace', cabinetName: 'Practice name', emailAddress: 'Email address', firstName: 'First name', lastName: 'Last name', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in...', creating: 'Creating...', startTrial: 'Start my free trial', haveAccount: 'I already have an account', createAccount: 'Create an account', welcome: 'Welcome!', loginSuccess: 'Signed in successfully', loginFailed: 'Sign-in failed', accessDenied: 'Access denied', invalidCredentials: 'Incorrect credentials', registrationFailed: 'Registration failed', emailRequired: 'Email is required', invalidEmail: 'Invalid email', passwordRequired: 'Password is required', minChars: 'Minimum 4 characters', demo: 'Demo: admin@practitioner.ma / admin123', practiceCreationRestricted: 'Shop creation is reserved for the super administrator.', headline: 'Run your practice like a pro', description: 'Track appointments, services and revenue in real time. A complete platform for doctors and their assistants.', revenueAccuracy: 'Revenue accuracy', availability: 'Availability', reports: 'Reports'
  },
  home: {
    servicesEyebrow: 'OUR SERVICES', title: 'My workspace', subtitle: 'Quick access to your tools.', appointments: 'Appointments', appointmentsDesc: 'View appointments and manage the queue.', newService: 'New service', newServiceDesc: 'Quickly charge for a service.', productSale: 'Product sale', productSaleDesc: 'Add products and complete the sale.', history: 'History', historyDesc: 'Services and products sold.', tickets: 'Tickets', ticketsDesc: 'Today’s services and products.'
  },
  appointment: {
    title: 'Appointments', subtitle: 'Planning and tracking', new: 'New appointment', edit: 'Edit appointment', next: 'Next appointment', todayHistory: 'Today’s history', todayCount: '{{count}} appointments', noWaiting: 'No clients waiting.', noToday: 'No appointments to process today', noHistory: 'No appointments in today’s history', waitingRoom: 'Waiting room', toProcess: 'To process', inProgress: 'In progress', completed: 'Completed', cancelled: 'Cancelled', absent: 'No-show', confirmed: 'Confirmed', clientArrived: 'Client arrived', start: 'Start', finish: 'Finish', newSuccess: 'Appointment created', editSuccess: 'Appointment updated', statusSuccess: 'Status updated', optionalClient: 'Client (optional)', selectPlaceholder: 'Select', practitionerRequired: 'Practitioner is required', serviceRequired: 'Service is required', dateRequired: 'Date is required', timeRequired: 'Time is required', more: '+{{count}} more', noActivePractitioner: 'No active practitioner.', anyPractitioner: 'Any practitioner', walkIn: 'Walk-in'
  },
  sale: {
    searchAll: 'Search for a service or product...', searchProduct: 'Search for a product...', order: 'Order ({{count}})', touchService: 'Tap a service to add it.', touchProduct: 'Tap a product to add it.', selectClient: 'Select', newClient: 'New client', noClient: 'No client found.', cash: 'Cash', card: 'Card', both: 'Both', checkout: 'Charge {{amount}}', serviceSaved: 'Service saved', productsSaved: 'Product sale saved', paymentMismatch: 'Payment total must match the sale total', noMatchingService: 'No services match your search.', noMatchingProduct: 'No products match your search.'
  },
  history: {
    title: 'Sales history', subtitle: 'View all your practice transactions.', dailyTicket: 'Daily ticket', periodTicket: 'Period ticket', totalSales: 'Total sales', transactionCount: 'Number of transactions', itemsSold: 'Items sold', averageTransaction: 'Average transaction', searchPlaceholder: 'Search transactions, clients or items...', period: 'Period', practitioner: 'Practitioner', service: 'Service', product: 'Product', payment: 'Payment', allPractitioners: 'All practitioners', allServices: 'All services', allProducts: 'All products', allPayments: 'All payment methods', transactions: 'Transactions', articles: 'Items', paymentMethod: 'Payment method', noMatch: 'No transactions match the filters.', display: 'Showing {{count}} transaction(s) · Page {{page}} of {{pages}}', previous: 'Previous', next: 'Next', saleDetails: 'Sale details', noClient: 'No client', practitionerCommission: 'Practitioner commission', cabinetRevenue: 'Shop revenue', ticket: 'Ticket'
  },
  payment: { CASH: 'Cash', CARD: 'Card', OTHER: 'Other' },
  queue: { title: 'Queue', subtitle: 'Clients with appointments and walk-ins', addClient: 'Add a client', empty: 'The queue is empty.', added: 'Client added to queue', addToQueue: 'Add to queue', chooseService: 'Choose a service', waitingMinutes: 'Waiting {{count}} min', arrivedMinutes: 'Arrived {{count}} min ago' },
  dashboard: { global: 'Global overview', globalDescription: 'Manage all practices and network activity.', cabinets: 'Cabinets', workspace: 'Choose your workspace', appointmentsDescription: 'View the calendar, arrivals and queue.', servicesDescription: 'Record a service using the checkout form.', performance: 'Performance', title: 'Dashboard', sevenDays: '7 days', thirtyDays: '30 days', from: 'From', to: 'To', noTransactions: 'No transactions for this period', date: 'Date', practitioner: 'Practitioner', client: 'Client', services: 'Service(s)', payment: 'Payment' },
  clients: { title: 'Clients', count: '{{count}} client(s) registered', search: 'Search by name or phone...', empty: 'No client found', new: 'New client', never: 'Never', visits: 'Visits', spent: 'Total spent', lastVisit: 'Last visit', created: 'Client created', firstName: 'First name', lastName: 'Last name', phone: 'Phone', email: 'Email' },
  productsPage: { title: 'Products', subtitle: 'Catalog of products for sale.', add: 'Add product', search: 'Search...', status: 'Status', all: 'All', active: 'Active', inactive: 'Inactive', table: 'Table', grid: 'Grid', empty: 'No products', addFirst: 'Add the first one', available: 'Available', new: 'New product', edit: 'Edit product', priceMad: 'Price (MAD) *', photo: 'Photo', remove: 'Remove', deleted: 'Product deleted', created: 'Product created', updated: 'Product updated', nameRequired: 'Name is required', priceInvalid: 'Invalid price' },
  servicesPage: { title: 'Service catalog', subtitle: 'Global services (SUPER_ADMIN)', add: 'Add service', search: 'Search...', category: 'Category', allCategories: 'All', status: 'Status', all: 'All', active: 'Active', inactive: 'Inactive', available: 'Available', unavailable: 'Unavailable', table: 'Table', grid: 'Grid', empty: 'No services in the catalog', addFirst: 'Add the first one', emptyCabinet: 'No services registered', createService: 'Create a service', addFromCatalog: 'Add from catalog', addService: 'Add service', service: 'Service', duration: 'Duration', price: 'Price', new: 'New service', edit: 'Edit service', newCabinet: 'New service', editCabinet: 'Edit service', nameRequired: 'Name is required', priceInvalid: 'Invalid price', durationInvalid: 'Invalid duration', added: 'Service added to catalog', created: 'Service created', updated: 'Service updated', statusUpdated: 'Status updated', photo: 'Photo', description: 'Description', activeService: 'Active service', availableService: 'Service available / active', remove: 'Remove', selectAll: 'Select all', catalogHelp: 'Select services and set their price for this practice.', alreadyAdded: 'Already added', changePhoto: 'Change photo', addPhoto: 'Add photo', upload: 'Uploading...', undefinedDuration: 'Duration not defined', clickPhoto: 'Click the photo', emptyCatalog: 'The catalog is empty.', save: 'Save', saving: 'Saving...', savedCount: 'Save ({{count}})', selectOne: 'Select at least one service', coupe: 'Haircut', barbe: 'Beard', forfait: 'Package', soin: 'Care', autre: 'Other' },
  practitionersPage: { title: 'Practitioners', subtitle: 'Manage your practice team', add: 'Add practitioner', empty: 'No practitioners registered', addFirst: 'Add the first one', created: 'Practitioner created successfully', updated: 'Practitioner updated successfully', activated: 'Practitioner activated', deactivated: 'Practitioner deactivated', firstNameRequired: 'First name is required', lastNameRequired: 'Last name is required', emailInvalid: 'Invalid email', rateRequired: '0-100% required', salaryInvalid: 'Invalid salary', disableTitle: 'Disable this practitioner?', enableTitle: 'Enable this practitioner?', disableDescription: 'They will no longer be selectable for new services.', enableDescription: 'They will be available for services again.', commission: 'Commission', salary: 'Fixed salary', mixed: 'Mixed' },
  salePage: { searchAll: 'Search for a service or product...', searchProduct: 'Search for a product...', select: 'Select', noPractitioner: 'No active practitioner.', noServiceMatch: 'No services match your search.', noProductMatch: 'No products match your search.', client: 'Client', close: 'Close', clientSearch: 'Name or phone', noClient: 'No client found.', newClient: 'New client', order: 'Order ({{count}})', touchProduct: 'a product', touchService: 'a service', subtotal: 'Subtotal', both: 'Both', paymentMismatch: 'Payment total must match the sale total', clientRequired: 'First name, last name and phone are required to create a client', savedProduct: 'Product sale saved', savedService: 'Service saved', checkout: 'Charge {{amount}}' },
  reportsPage: { title: 'Reports', subtitle: 'Detailed daily report', reportDate: 'Report date', print: 'Print', download: 'Download PDF', loadDate: 'Load a date to view the report', daily: 'Daily report', revenue: 'Revenue', services: 'Services', commissions: 'Commissions', net: 'Net revenue', breakdown: 'Breakdown by practitioner', noPractitioners: 'No practitioners for this period', details: 'Transaction details ({{count}})', noTransactions: 'No transactions', hour: 'Time', cabinetRevenue: 'Shop revenue' },
  payrollPage: { title: 'Payroll', subtitle: 'Calculate commissions and track practitioner payments.', newPeriod: 'New period', start: 'Start', end: 'End', create: 'Create and calculate', created: 'Period created', base: 'Base', net: 'Net', paid: 'Paid', approved: 'Approved', pending: 'Pending', range: 'to' },
  adminPage: { usersTitle: 'Users', newUser: 'New user', noUsers: 'No users', created: 'User created', updated: 'User updated', deleted: 'User deleted', createFailed: 'Creation failed', deleteFailed: 'Deletion failed', deleteUser: 'Delete user?', deleteUserDescription: 'This action disables the user and removes them from the list.', planPricing: 'Pricing', planPricingSubtitle: 'Choose the right plan for your practice.', noPlans: 'No plans available', current: 'Current', perMonth: '/ month', commitment: '{{months}} month commitment', users: '{{count}} users', practitioners: '{{count}} practitioners', currentPlan: 'Current plan', choose: 'Choose', permissions: 'Permissions', permissionSubtitle: 'Configure permissions by role. They are filtered by plan permissions.', role: 'Role', newRole: 'New role', delete: 'Delete', selectAll: 'Select all', deselectAll: 'Deselect all', saved: 'Permissions updated', deletedRole: 'Role deleted' },
  settings: { subtitle: 'Manage your practice information and account', cabinetTab: 'Shop', accountTab: 'Account', billingTab: 'Subscription', cabinetInfo: 'Shop information', cabinetInfoDescription: 'This information will appear on tickets and reports.', cabinetName: 'Practice name', address: 'Address', currency: 'Currency', save: 'Save', billingDescription: 'Manage the practice plan and automatic renewal.', expiredOn: 'Expired on {{date}}', expiresToday: 'Expires today ({{date}})', expiresIn: 'Expires on {{date}} ({{days}} day(s) left)', noExpiration: 'Expiration: Not defined', upgrade: 'Upgrade', renew: 'Renew', noPlan: 'No plan associated.', choosePlan: 'Choose a plan', profile: 'User profile', profileDescription: 'Your login information', changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', changePasswordButton: 'Change password', passwordMismatch: 'Passwords do not match', saved: 'Information saved' },
  table: { rank: '#', practitioner: 'Practitioner', serviceCount: 'Services', revenue: 'Revenue', commission: 'Commission', performance: 'Performance', phone: 'Phone', remuneration: 'Compensation', rateSalary: 'Rate / Salary', date: 'Date', items: 'Items', paymentMethod: 'Payment method', total: 'Total', cabinet: 'Cabinet', plan: 'Plan', users: 'Users', clients: 'Clients', user: 'User', admin: 'Admin', role: 'Role', limits: 'Limits', permissions: 'Permissions', actions: 'Actions', hour: 'Time', cabinetRevenue: 'Shop revenue' },
  status: { PENDING: 'To process', CONFIRMED: 'Confirmed', REMINDER_SENT: 'Reminder sent', WAITING: 'Waiting room', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', CANCELLED: 'Cancelled', NO_SHOW: 'No-show' },
  errors: { notFoundTitle: 'Page not found', notFoundDescription: 'This page does not exist or has moved. Go back home to continue.', permissionTitle: 'Permission denied', permissionDescription: 'You are not authorized to access this page.' },
  crud: {
    addFromCatalog: 'Add from catalog', addService: 'Add service', addProduct: 'Add product', newService: 'New service', newProduct: 'New product', catalogTitle: 'Service catalog', catalogHelp: 'Select services and set their price for this practice.', selectAll: 'Select all', alreadyAdded: 'Already added', clickPhoto: 'Click the photo', addPhoto: 'Add photo', changePhoto: 'Change photo', upload: 'Uploading...', recordCount: '{{count}} item(s) saved', emptyCatalog: 'The catalog is empty.', ratesServices: 'Rates and offered services'
  }
}

const ar = {
  common: {
    back: 'رجوع', add: 'إضافة', create: 'إنشاء', edit: 'تعديل', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', close: 'إغلاق', search: 'بحث', select: 'اختيار', all: 'الكل', none: 'لا يوجد', yes: 'نعم', no: 'لا', active: 'نشط', inactive: 'غير نشط', available: 'متاح', unavailable: 'غير متاح', actions: 'الإجراءات', status: 'الحالة', date: 'التاريخ', time: 'الوقت', client: 'العميل', practitioner: 'الطبيب', service: 'الخدمة', services: 'الخدمات', product: 'المنتج', products: 'المنتجات', price: 'السعر', duration: 'المدة', category: 'الفئة', phone: 'الهاتف', email: 'البريد الإلكتروني', name: 'الاسم', firstName: 'الاسم الأول', lastName: 'اسم العائلة', password: 'كلمة المرور', notes: 'ملاحظات', total: 'المجموع', subtotal: 'المجموع الفرعي', payment: 'الدفع', loading: 'جارٍ التحميل...', error: 'خطأ', success: 'نجاح', required: 'مطلوب', today: 'اليوم', yesterday: 'أمس', week: 'هذا الأسبوع', month: 'هذا الشهر', customPeriod: 'فترة مخصصة', noData: 'لا توجد بيانات', reset: 'إعادة ضبط', view: 'عرض', print: 'طباعة', profile: 'الملف الشخصي', logout: 'تسجيل الخروج', language: 'اللغة', french: 'Français', english: 'English', arabic: 'العربية'
  },
  nav: {
    invoices: 'الفواتير', messages: 'الرسائل', audit: 'سجل التدقيق', home: 'الرئيسية', dashboard: 'لوحة التحكم', allCabinets: 'كل المتاجر', practitioners: 'الأطباء', services: 'الخدمات', products: 'المنتجات', productSales: 'مبيعات المنتجات', appointments: 'المواعيد', clients: 'العملاء', history: 'السجل', myServices: 'خدماتي', myStats: 'إحصائياتي', users: 'المستخدمون', plans: 'خطط SaaS', payroll: 'الرواتب', settings: 'الإعدادات', permissions: 'الصلاحيات', administration: 'الإدارة', selectedCabinet: 'العيادة المحدد', openMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة'
  },
  roles: { admin: 'مسؤول', superAdmin: 'المسؤول العام', practitioner: 'طبيب' },
  auth: {
    login: 'تسجيل الدخول', register: 'إنشاء مساحة العمل', subtitle: 'ادخل إلى مساحة إدارة متجرك', cabinetName: 'اسم العيادة', emailAddress: 'البريد الإلكتروني', firstName: 'الاسم الأول', lastName: 'اسم العائلة', password: 'كلمة المرور', signIn: 'تسجيل الدخول', signingIn: 'جارٍ الدخول...', creating: 'جارٍ الإنشاء...', startTrial: 'ابدأ التجربة المجانية', haveAccount: 'لدي حساب بالفعل', createAccount: 'إنشاء حساب', welcome: 'مرحباً!', loginSuccess: 'تم تسجيل الدخول', loginFailed: 'فشل تسجيل الدخول', accessDenied: 'تم رفض الوصول', invalidCredentials: 'بيانات الدخول غير صحيحة', registrationFailed: 'فشل التسجيل', emailRequired: 'البريد الإلكتروني مطلوب', invalidEmail: 'البريد الإلكتروني غير صالح', passwordRequired: 'كلمة المرور مطلوبة', minChars: 'الحد الأدنى 4 أحرف', demo: 'تجربة: admin@practitioner.ma / admin123', practiceCreationRestricted: 'إنشاء المتاجر مخصص للمسؤول العام.', headline: 'عيادتك الطبية ببساطة', description: 'تابع المواعيد والخدمات والإيرادات لحظة بلحظة. منصة متكاملة للأطباء ومساعديهم.', revenueAccuracy: 'دقة الإيرادات', availability: 'التوفر', reports: 'التقارير'
  },
  home: {
    servicesEyebrow: 'خدماتنا', title: 'مساحتي', subtitle: 'وصول سريع إلى الأدوات.', appointments: 'المواعيد', appointmentsDesc: 'عرض المواعيد وإدارة قائمة الانتظار.', newService: 'خدمة جديدة', newServiceDesc: 'تحصيل ثمن الخدمة بسرعة.', productSale: 'بيع المنتجات', productSaleDesc: 'إضافة المنتجات وإتمام البيع.', history: 'السجل', historyDesc: 'الخدمات والمنتجات المباعة.', tickets: 'التذاكر', ticketsDesc: 'خدمات ومنتجات اليوم.'
  },
  appointment: {
    title: 'المواعيد', subtitle: 'التخطيط والمتابعة', new: 'موعد جديد', edit: 'تعديل الموعد', next: 'الموعد التالي', todayHistory: 'سجل اليوم', todayCount: '{{count}} موعد', noWaiting: 'لا يوجد عملاء في الانتظار.', noToday: 'لا توجد مواعيد للمعالجة اليوم', noHistory: 'لا توجد مواعيد في سجل اليوم', waitingRoom: 'قاعة الانتظار', toProcess: 'قيد المعالجة', inProgress: 'قيد التنفيذ', completed: 'مكتمل', cancelled: 'ملغي', absent: 'غائب', confirmed: 'مؤكد', clientArrived: 'وصل العميل', start: 'بدء', finish: 'إنهاء', newSuccess: 'تم إنشاء الموعد', editSuccess: 'تم تعديل الموعد', statusSuccess: 'تم تحديث الحالة', optionalClient: 'العميل (اختياري)', selectPlaceholder: 'اختر', practitionerRequired: 'الطبيب مطلوب', serviceRequired: 'الخدمة مطلوبة', dateRequired: 'التاريخ مطلوب', timeRequired: 'الوقت مطلوب', more: '+{{count}} أخرى', noActivePractitioner: 'لا يوجد طبيب نشط.', anyPractitioner: 'أي طبيب', walkIn: 'بدون موعد'
  },
  sale: {
    searchAll: 'ابحث عن خدمة أو منتج...', searchProduct: 'ابحث عن منتج...', order: 'الطلب ({{count}})', touchService: 'اضغط على خدمة لإضافتها.', touchProduct: 'اضغط على منتج لإضافته.', selectClient: 'اختيار', newClient: 'عميل جديد', noClient: 'لم يتم العثور على عميل.', cash: 'نقداً', card: 'بطاقة', both: 'كلاهما', checkout: 'تحصيل {{amount}}', serviceSaved: 'تم حفظ الخدمة', productsSaved: 'تم حفظ بيع المنتجات', paymentMismatch: 'يجب أن يساوي مجموع الدفعات إجمالي البيع', noMatchingService: 'لا توجد خدمات مطابقة للبحث.', noMatchingProduct: 'لا توجد منتجات مطابقة للبحث.'
  },
  history: {
    title: 'سجل المبيعات', subtitle: 'عرض جميع معاملات العيادة.', dailyTicket: 'تذكرة اليوم', periodTicket: 'تذكرة الفترة', totalSales: 'إجمالي المبيعات', transactionCount: 'عدد المعاملات', itemsSold: 'العناصر المباعة', averageTransaction: 'متوسط المعاملة', searchPlaceholder: 'ابحث في المعاملات والعملاء والعناصر...', period: 'الفترة', practitioner: 'الطبيب', service: 'الخدمة', product: 'المنتج', payment: 'الدفع', allPractitioners: 'كل الأطباء', allServices: 'كل الخدمات', allProducts: 'كل المنتجات', allPayments: 'كل طرق الدفع', transactions: 'المعاملات', articles: 'العناصر', paymentMethod: 'طريقة الدفع', noMatch: 'لا توجد معاملات مطابقة للفلاتر.', display: 'عرض {{count}} معاملة · الصفحة {{page}} من {{pages}}', previous: 'السابق', next: 'التالي', saleDetails: 'تفاصيل البيع', noClient: 'بدون عميل', practitionerCommission: 'عمولة الطبيب', cabinetRevenue: 'إيراد العيادة', ticket: 'تذكرة'
  },
  payment: { CASH: 'نقداً', CARD: 'بطاقة', OTHER: 'أخرى' },
  queue: { title: 'قائمة الانتظار', subtitle: 'العملاء أصحاب المواعيد والعملاء بدون موعد', addClient: 'إضافة عميل', empty: 'قائمة الانتظار فارغة.', added: 'تمت إضافة العميل إلى القائمة', addToQueue: 'إضافة إلى القائمة', chooseService: 'اختر خدمة', waitingMinutes: 'انتظار {{count}} دقيقة', arrivedMinutes: 'وصل منذ {{count}} دقيقة' },
  dashboard: { global: 'نظرة عامة', globalDescription: 'إدارة جميع المتاجر ونشاط الشبكة.', cabinets: 'المتاجر', workspace: 'اختر مساحة العمل', appointmentsDescription: 'عرض التقويم ووصول العملاء وقائمة الانتظار.', servicesDescription: 'تسجيل خدمة باستخدام نموذج الصندوق.', performance: 'الأداء', title: 'لوحة التحكم', sevenDays: '7 أيام', thirtyDays: '30 يوماً', from: 'من', to: 'إلى', noTransactions: 'لا توجد معاملات خلال هذه الفترة', date: 'التاريخ', practitioner: 'الطبيب', client: 'العميل', services: 'الخدمات', payment: 'الدفع' },
  clients: { title: 'العملاء', count: '{{count}} عميل مسجل', search: 'ابحث بالاسم أو الهاتف...', empty: 'لم يتم العثور على عميل', new: 'عميل جديد', never: 'أبداً', visits: 'الزيارات', spent: 'إجمالي الإنفاق', lastVisit: 'آخر زيارة', created: 'تم إنشاء العميل', firstName: 'الاسم الأول', lastName: 'اسم العائلة', phone: 'الهاتف', email: 'البريد الإلكتروني' },
  productsPage: { title: 'المنتجات', subtitle: 'كتالوج المنتجات القابلة للبيع.', add: 'إضافة منتج', search: 'بحث...', status: 'الحالة', all: 'الكل', active: 'نشط', inactive: 'غير نشط', table: 'جدول', grid: 'شبكة', empty: 'لا توجد منتجات', addFirst: 'إضافة الأول', available: 'متاح', new: 'منتج جديد', edit: 'تعديل المنتج', priceMad: 'السعر (MAD) *', photo: 'الصورة', remove: 'إزالة', deleted: 'تم حذف المنتج', created: 'تم إنشاء المنتج', updated: 'تم تعديل المنتج', nameRequired: 'الاسم مطلوب', priceInvalid: 'السعر غير صالح' },
  servicesPage: { title: 'كتالوج الخدمات', subtitle: 'الخدمات العامة (المسؤول العام)', add: 'إضافة خدمة', search: 'بحث...', category: 'الفئة', allCategories: 'الكل', status: 'الحالة', all: 'الكل', active: 'نشط', inactive: 'غير نشط', available: 'متاح', unavailable: 'غير متاح', table: 'جدول', grid: 'شبكة', empty: 'لا توجد خدمات في الكتالوج', addFirst: 'إضافة الأول', emptyCabinet: 'لا توجد خدمات مسجلة', createService: 'إنشاء خدمة', addFromCatalog: 'إضافة من الكتالوج', addService: 'إضافة خدمة', service: 'الخدمة', duration: 'المدة', price: 'السعر', new: 'خدمة جديدة', edit: 'تعديل الخدمة', newCabinet: 'خدمة جديدة', editCabinet: 'تعديل الخدمة', nameRequired: 'الاسم مطلوب', priceInvalid: 'السعر غير صالح', durationInvalid: 'المدة غير صالحة', added: 'تمت إضافة الخدمة إلى الكتالوج', created: 'تم إنشاء الخدمة', updated: 'تم تعديل الخدمة', statusUpdated: 'تم تحديث الحالة', photo: 'الصورة', description: 'الوصف', activeService: 'خدمة نشطة', availableService: 'الخدمة متاحة / نشطة', remove: 'إزالة', selectAll: 'اختيار الكل', catalogHelp: 'اختر الخدمات وحدد سعرها لهذا العيادة.', alreadyAdded: 'مضافة مسبقاً', changePhoto: 'تغيير الصورة', addPhoto: 'إضافة صورة', upload: 'جارٍ الرفع...', undefinedDuration: 'المدة غير محددة', clickPhoto: 'اضغط على الصورة', emptyCatalog: 'الكتالوج فارغ.', save: 'حفظ', saving: 'جارٍ الحفظ...', savedCount: 'حفظ ({{count}})', selectOne: 'اختر خدمة واحدة على الأقل', coupe: 'طبيبة', barbe: 'لحية', forfait: 'باقة', soin: 'عناية', autre: 'أخرى' },
  practitionersPage: { title: 'الأطباء', subtitle: 'إدارة فريق العيادة', add: 'إضافة طبيب', empty: 'لا يوجد طبيبون مسجلون', addFirst: 'إضافة الأول', created: 'تم إنشاء الطبيب بنجاح', updated: 'تم تعديل الطبيب بنجاح', activated: 'تم تفعيل الطبيب', deactivated: 'تم تعطيل الطبيب', firstNameRequired: 'الاسم الأول مطلوب', lastNameRequired: 'اسم العائلة مطلوب', emailInvalid: 'البريد الإلكتروني غير صالح', rateRequired: 'مطلوب من 0 إلى 100٪', salaryInvalid: 'الراتب غير صالح', disableTitle: 'تعطيل هذا الطبيب؟', enableTitle: 'تفعيل هذا الطبيب؟', disableDescription: 'لن يكون متاحاً للخدمات الجديدة.', enableDescription: 'سيصبح متاحاً للخدمات مجدداً.', commission: 'عمولة', salary: 'راتب ثابت', mixed: 'مختلط' },
  salePage: { searchAll: 'ابحث عن خدمة أو منتج...', searchProduct: 'ابحث عن منتج...', select: 'اختيار', noPractitioner: 'لا يوجد طبيب نشط.', noServiceMatch: 'لا توجد خدمات مطابقة للبحث.', noProductMatch: 'لا توجد منتجات مطابقة للبحث.', client: 'العميل', close: 'إغلاق', clientSearch: 'الاسم أو الهاتف', noClient: 'لم يتم العثور على عميل.', newClient: 'عميل جديد', order: 'الطلب ({{count}})', touchProduct: 'منتج', touchService: 'خدمة', subtotal: 'المجموع الفرعي', both: 'كلاهما', paymentMismatch: 'يجب أن يساوي مجموع الدفعات إجمالي البيع', clientRequired: 'الاسم الأول واسم العائلة والهاتف مطلوبة لإنشاء عميل', savedProduct: 'تم حفظ بيع المنتجات', savedService: 'تم حفظ الخدمة', checkout: 'تحصيل {{amount}}' },
  reportsPage: { title: 'التقارير', subtitle: 'تقرير يومي مفصل', reportDate: 'تاريخ التقرير', print: 'طباعة', download: 'تحميل PDF', loadDate: 'اختر تاريخاً لعرض التقرير', daily: 'التقرير اليومي', revenue: 'الإيرادات', services: 'الخدمات', commissions: 'العمولات', net: 'صافي الإيرادات', breakdown: 'التفصيل حسب الطبيب', noPractitioners: 'لا يوجد طبيبون خلال هذه الفترة', details: 'تفاصيل المعاملات ({{count}})', noTransactions: 'لا توجد معاملات', hour: 'الوقت', cabinetRevenue: 'إيراد العيادة' },
  payrollPage: { title: 'الرواتب', subtitle: 'احسب العمولات وتابع مدفوعات الأطباء.', newPeriod: 'فترة جديدة', start: 'البداية', end: 'النهاية', create: 'إنشاء وحساب', created: 'تم إنشاء الفترة', base: 'الأساس', net: 'الصافي', paid: 'مدفوع', approved: 'معتمد', pending: 'قيد الانتظار', range: 'إلى' },
  adminPage: { usersTitle: 'المستخدمون', newUser: 'مستخدم جديد', noUsers: 'لا يوجد مستخدمون', created: 'تم إنشاء المستخدم', updated: 'تم تحديث المستخدم', deleted: 'تم حذف المستخدم', createFailed: 'فشل الإنشاء', deleteFailed: 'فشل الحذف', deleteUser: 'حذف المستخدم؟', deleteUserDescription: 'سيؤدي هذا الإجراء إلى تعطيل المستخدم وإزالته من القائمة.', planPricing: 'الأسعار', planPricingSubtitle: 'اختر الخطة المناسبة لمتجرك.', noPlans: 'لا توجد خطط متاحة', current: 'الحالية', perMonth: '/ شهرياً', commitment: 'التزام لمدة {{months}} شهراً', users: '{{count}} مستخدم', practitioners: '{{count}} طبيب', currentPlan: 'الخطة الحالية', choose: 'اختيار', permissions: 'الصلاحيات', permissionSubtitle: 'إعداد الصلاحيات حسب الدور. سيتم تصفيتها حسب صلاحيات الخطة.', role: 'الدور', newRole: 'دور جديد', delete: 'حذف', selectAll: 'اختيار الكل', deselectAll: 'إلغاء اختيار الكل', saved: 'تم تحديث الصلاحيات', deletedRole: 'تم حذف الدور' },
  settings: { subtitle: 'إدارة معلومات العيادة والحساب', cabinetTab: 'العيادة', accountTab: 'الحساب', billingTab: 'الاشتراك', cabinetInfo: 'معلومات العيادة', cabinetInfoDescription: 'ستظهر هذه المعلومات على التذاكر والتقارير.', cabinetName: 'اسم العيادة', address: 'العنوان', currency: 'العملة', save: 'حفظ', billingDescription: 'إدارة خطة العيادة والتجديد التلقائي.', expiredOn: 'انتهى في {{date}}', expiresToday: 'ينتهي اليوم ({{date}})', expiresIn: 'ينتهي في {{date}} (متبقي {{days}} يوم)', noExpiration: 'انتهاء الصلاحية: غير محدد', upgrade: 'ترقية', renew: 'تجديد', noPlan: 'لا توجد خطة مرتبطة.', choosePlan: 'اختيار خطة', profile: 'ملف المستخدم', profileDescription: 'معلومات تسجيل الدخول الخاصة بك', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', confirmPassword: 'تأكيد كلمة المرور الجديدة', changePasswordButton: 'تغيير كلمة المرور', passwordMismatch: 'كلمتا المرور غير متطابقتين', saved: 'تم حفظ المعلومات' },
  table: { rank: '#', practitioner: 'الطبيب', serviceCount: 'الخدمات', revenue: 'الإيرادات', commission: 'العمولة', performance: 'الأداء', phone: 'الهاتف', remuneration: 'التعويض', rateSalary: 'النسبة / الراتب', date: 'التاريخ', items: 'العناصر', paymentMethod: 'طريقة الدفع', total: 'المجموع', cabinet: 'العيادة', plan: 'الخطة', users: 'المستخدمون', clients: 'العملاء', user: 'المستخدم', admin: 'المسؤول', role: 'الدور', limits: 'الحدود', permissions: 'الصلاحيات', actions: 'الإجراءات', hour: 'الوقت', cabinetRevenue: 'إيراد العيادة' },
  status: { PENDING: 'قيد المعالجة', CONFIRMED: 'مؤكد', REMINDER_SENT: 'تم إرسال التذكير', WAITING: 'قاعة الانتظار', IN_PROGRESS: 'قيد التنفيذ', COMPLETED: 'مكتمل', CANCELLED: 'ملغي', NO_SHOW: 'غائب' },
  errors: { notFoundTitle: 'الصفحة غير موجودة', notFoundDescription: 'هذه الصفحة غير موجودة أو تم نقلها. عد إلى الرئيسية للمتابعة.', permissionTitle: 'تم رفض الإذن', permissionDescription: 'ليس لديك صلاحية الوصول إلى هذه الصفحة.' },
  crud: {
    addFromCatalog: 'إضافة من الكتالوج', addService: 'إضافة خدمة', addProduct: 'إضافة منتج', newService: 'خدمة جديدة', newProduct: 'منتج جديد', catalogTitle: 'كتالوج الخدمات', catalogHelp: 'اختر الخدمات وحدد سعرها لهذا العيادة.', selectAll: 'اختيار الكل', alreadyAdded: 'مضافة مسبقاً', clickPhoto: 'اضغط على الصورة', addPhoto: 'إضافة صورة', changePhoto: 'تغيير الصورة', upload: 'جارٍ الرفع...', recordCount: 'تم حفظ {{count}} عنصر', emptyCatalog: 'الكتالوج فارغ.', ratesServices: 'الأسعار والخدمات المقدمة'
  }
}

// Later dictionaries win; nested sections (nav, roles...) are merged key by key.
function merge(...dicts: Record<string, any>[]) {
  const out: Record<string, any> = {}
  for (const dict of dicts) {
    for (const [key, value] of Object.entries(dict)) {
      out[key] = value && typeof value === 'object' && !Array.isArray(value) ? { ...(out[key] || {}), ...value } : value
    }
  }
  return out
}

const savedLanguage = localStorage.getItem('cabinet-pro-language')
const language: AppLanguage = supportedLanguages.includes(savedLanguage as AppLanguage) ? savedLanguage as AppLanguage : 'fr'

void i18n.use(initReactI18next).init({
  resources: {
    fr: { translation: merge(fr, frExtra, frMedical, frSimple) },
    en: { translation: merge(en, enExtra, enMedical, enSimple) },
    ar: { translation: merge(ar, arExtra, arMedical, arSimple) },
  },
  lng: language,
  fallbackLng: 'fr',
  interpolation: { escapeValue: false },
})

export function applyDocumentLanguage(nextLanguage: string) {
  const normalized = supportedLanguages.includes(nextLanguage as AppLanguage) ? nextLanguage as AppLanguage : 'fr'
  document.documentElement.lang = normalized
  document.documentElement.dir = normalized === 'ar' ? 'rtl' : 'ltr'
  localStorage.setItem('cabinet-pro-language', normalized)
}

applyDocumentLanguage(language)
i18n.on('languageChanged', applyDocumentLanguage)

export default i18n
